site_name: "Qtile"
site_description: "A pure-Python tiling window manager."
site_url: "https://qtile.org/"
repo_url: "https://github.com/qtile/qtile"
repo_name: "Qtile"
site_dir: "site"
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG, libqtile]
copyright: Copyright 2008, Aldo Cortesi and contributors
edit_uri: edit/master/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
- Getting Started:
  - Installation:
    - manual/install/index.md
    - Arch: manual/install/arch.md
    - Fedora: manual/install/fedora.md
    - Funtoo: manual/install/funtoo.md
    - Ubuntu/Debian: manual/install/ubuntu.md
    - Slackware: manual/install/slackware.md
    - FreeBSD: manual/install/freebsd.md
    - NixOS: manual/install/nixos.md
  - Wayland: manual/wayland.md
  - Troubleshooting: manual/troubleshooting.md
  - Entry points: manual/commands/shell/index.md
- Scripting:
  - Architecture: manual/commands/index.md
  - Interfaces: manual/commands/interfaces.md
  - Commands API:
    - manual/commands/api/index.md
    - Qtile root: manual/commands/api/root.md
    - Layouts: manual/commands/api/layouts.md
    - Windows: manual/commands/api/windows.md
    - Groups: manual/commands/api/groups.md
    - Bars: manual/commands/api/bars.md
    - Widgets: manual/commands/api/widgets.md
    - Screens: manual/commands/api/screens.md
    - Core: manual/commands/api/backend.md
- Configuration:
  - Default configuration file: manual/config/default.md
  - The configuration file: manual/config/index.md
  - Built-in Layouts: manual/ref/layouts.md
  - Built-in Widgets: manual/ref/widgets.md
  - Built-in Hooks: manual/ref/hooks.md
  - Built-in Extensions: manual/ref/extensions.md
  - Keybindings in images: manual/commands/keybindings.md
  - Window stacking: manual/stacking.md
- Hacking:
  - Hacking on Qtile: manual/hacking.md
  - Contributing: manual/contributing.md
- Miscellaneous:
  - Frequently Asked Questions: manual/faq.md
  - How to create a widget: manual/howto/widget.md
  - Using `git`: manual/howto/git.md
  - License: manual/license.md
  - Changelog: manual/changelog.md

theme:
  name: material
  icon:
    logo: fontawesome/solid/q
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.sections
  # - navigation.tabs
  # - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue grey
    accent: teal
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue grey
    accent: teal
    toggle:
      icon: material/weather-night
      name: Switch to system preference

extra_css:
- _static/material.css
- _static/mkdocstrings.css

markdown_extensions:
- attr_list
- admonition
- callouts
- footnotes
- markdown_grid_tables
- mkdocs_graphviz
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.magiclink
- pymdownx.snippets:
    base_path: [!relative $config_dir]
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- toc:
    permalink: true

plugins:
- search
- autorefs
- markdown-exec
# - gen-files:
#     scripts:
#     - scripts/gen_ref_nav.py
# - literate-nav:
#     nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        paths: [.]
        setup_commands:
        - import docs.mocks
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          extensions:
          - scripts/griffe_extensions.py
          filters: ["!^_"]
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_source: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          summary: true
- minify:
    minify_html: !ENV [DEPLOY, false]
# - group:
#     enabled: !ENV [MATERIAL_INSIDERS, false]
#     plugins:
#     - typeset

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/qtile
  - icon: fontawesome/brands/discord
    link: https://discord.gg/ehh233wCrC
  # - icon: fontawesome/brands/mastodon
  #   link: https://fosstodon.org/@qtile
  # - icon: fontawesome/brands/twitter
  #   link: https://twitter.com/qtile
  # - icon: fontawesome/brands/gitter
  #   link: https://gitter.im/qtile
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/qtile/
